/*import {
	PRODUCER_CHANGE_DETAIL,
	PRODUCER_CLEAR_DETAIL,
	PRODUCER_FORM_CHANGE_FOCUS,
	PRODUCER_FORM_CHANGE,
	PRODUCER_FORM_VALIDATION,
	PRODUCER_FORM_CLEAR,
	PRODUCER_FORM_CHANGE_MODE,
	PRODUCER_FORM_CHANGE_LOADING,
	PRODUCER_FORM_CLEAR_ALL
} from '../types';*/

const INITIAL_STATE = {};

const Reducer = (state = INITIAL_STATE, action) => {
	switch(action.type){
		
	}
	return state;
};

module.exports = Reducer;